/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crowdfundingSol from "./Crowdfunding.sol";
export type { crowdfundingSol };
export type { Governance } from "./Governance";
export type { IGovernance } from "./IGovernance";
export type { IProposals } from "./IProposals";
export type { ITimelock } from "./ITimelock";
export type { Timelock } from "./Timelock";
export type { TokenUF } from "./TokenUF";
