/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CrowdfundingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createCampaign"
      | "dao"
      | "getAllCampaigns"
      | "numberOfCampaigns"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CompaignStarted"): EventFragment;

  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "dao", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllCampaigns",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfCampaigns",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dao", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfCampaigns",
    data: BytesLike
  ): Result;
}

export namespace CompaignStartedEvent {
  export type InputTuple = [
    id: BigNumberish,
    campaign: AddressLike,
    orginazer: AddressLike,
    goal: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    campaign: string,
    orginazer: string,
    goal: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    id: bigint;
    campaign: string;
    orginazer: string;
    goal: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Crowdfunding extends BaseContract {
  connect(runner?: ContractRunner | null): Crowdfunding;
  waitForDeployment(): Promise<this>;

  interface: CrowdfundingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createCampaign: TypedContractMethod<
    [
      title: string,
      description: string,
      category: string,
      goal: BigNumberish,
      deadline: BigNumberish,
      image: string
    ],
    [void],
    "nonpayable"
  >;

  dao: TypedContractMethod<[], [string], "view">;

  getAllCampaigns: TypedContractMethod<[], [string[]], "view">;

  numberOfCampaigns: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      category: string,
      goal: BigNumberish,
      deadline: BigNumberish,
      image: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dao"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllCampaigns"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "numberOfCampaigns"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CompaignStarted"
  ): TypedContractEvent<
    CompaignStartedEvent.InputTuple,
    CompaignStartedEvent.OutputTuple,
    CompaignStartedEvent.OutputObject
  >;

  filters: {
    "CompaignStarted(uint256,address,address,uint256,uint256)": TypedContractEvent<
      CompaignStartedEvent.InputTuple,
      CompaignStartedEvent.OutputTuple,
      CompaignStartedEvent.OutputObject
    >;
    CompaignStarted: TypedContractEvent<
      CompaignStartedEvent.InputTuple,
      CompaignStartedEvent.OutputTuple,
      CompaignStartedEvent.OutputObject
    >;
  };
}
